Fetch prices from the API
scylladb/scylla-price-calculator pull request #21
Opened 2021-12-22 15:07 UTC by kamilCase

Fetches prices from the API, instead of using hardcoded values. Should be helpful, as from now on, the calculator would not need to be updated once there is a change in pricing.

TODO:
- clarify what's the proper formula for on demand and reserved prices.
- handle price fetch failure (retry/show error message)
- add a possibility to use variable API endpoints (is it needed or the one provided in the config is enough?)

2021-12-22 15:36 UTC, omrivardi reviewed
Awesome!

Since we don't have the full API yet and seem to have some issues in the current, see my suggestion for now.

I suggest doing some intermediate half manual solution for now, which will remove the stress.

Once we have all the data in the API, we could easily switch to use it and drop all manual mappings and subscriptions logic

2021-12-22 15:36 UTC, omrivardi commented on lib/src/config.js
> +  AWS_PRICING_URL: 'http://back.lab.dbaas.scyop.net:8080/api/v1/deployment/provider/1/instance',
We need to figure prod address and if it is open in the same manner.
Perhaps we can break it to baseURL + path to easily switch envs while developing.

2021-12-22 15:36 UTC, omrivardi commented on lib/src/models/ScyllaCloud.ts
> +            reserved: Number(instance.SubscriptionCostMonthly)
Right now it is not supported as part of the API.
If we can't push it soon, I suggest having manual mapping for this specific fields as an intermediate solution. Once the API will support it we will switch.

I'll reach out to you once I'll find where to get it from

2021-12-22 15:36 UTC, omrivardi commented on lib/src/config.js
> +  AWS_PRICING_URL: 'http://back.lab.dbaas.scyop.net:8080/api/v1/deployment/provider/1/instance',
There seems to be some recent change in the API and the default endpoint doesn't return costPerHour.
Let's use http://back.lab.dbaas.scyop.net:8080/api/v1/deployment/provider/1/region/1/instance here which should give the correct details.

2021-12-22 15:36 UTC, omrivardi commented on lib/src/config.js
> +  GCP_PRICING_URL: 'http://back.lab.dbaas.scyop.net:8080/api/v1/deployment/provider/2/instance'
And this will be http://back.lab.dbaas.scyop.net:8080/api/v1/deployment/provider/2/region/30/instance

2021-12-22 15:36 UTC, omrivardi commented on lib/src/models/ScyllaCloud.ts
> +            ondemand: Number(instance.SubscriptionCostMonthly),
This should be costPerHour

2021-12-22 15:36 UTC, omrivardi commented on lib/src/models/ScyllaCloud.ts
> +            total: compute + license // In the new pricing, data transfer fees included in subscription price
Once we validate the API subsciption costs, we could simply use the data there and remove all subscription cost calculations.

For now, let's keep it as is.

2021-12-22 15:50 UTC, omrivardi commented on lib/src/models/ScyllaCloud.ts
> +    const results = await Promise.all([awsResults.then(res=>res.json()), gcpResults.then(res=>res.json())]);
@AdarBahar Are there some instances we should filter out like development clusters?

2021-12-23 07:54 UTC, omrivardi commented on lib/src/config.js
> +  AWS_PRICING_URL: 'http://back.lab.dbaas.scyop.net:8080/api/v1/deployment/provider/1/instance',
Backend prod is not open...
We can use the frontend node server:
https://cloud.scylladb.com/deployment/cloud-provider/1/region/1

2021-12-23 08:01 UTC, omrivardi commented on lib/src/models/ScyllaCloud.ts
> +    const results = await Promise.all([awsResults.then(res=>res.json()), gcpResults.then(res=>res.json())]);
I don't see them in the old mapping. Let's filter `environment !== "DEVELOPMENT"`

2021-12-23 08:12 UTC, omrivardi commented on lib/src/models/ScyllaCloud.ts
> +            reserved: Number(instance.SubscriptionCostMonthly)
Here is a mapping from externalId to the cost of the instance, reserved monthly:
```
{
  'i3.large': 72.5,
  'i3.xlarge': 145.08,
  'i3.2xlarge': 290.17,
  'i3.4xlarge': 580.33,
  'i3.8xlarge': 1160.67,
  'i3.16xlarge': 2321.33,
  'i3en.large': 104.83,
  'i3en.xlarge': 209.75,
  'i3en.2xlarge': 419.5,
  'i3en.3xlarge': 629.25,
  'i3en.6xlarge': 1258.42,
  'i3en.12xlarge': 2516.83,
  'i3en.24xlarge': 5033.75,
  'n2-highmem-2': 79.405,
  'n2-highmem-4': 158.81,
  'n2-highmem-8': 317.62,
  'n2-highmem-16': 635.24,
}
```

2021-12-23 12:15 UTC, kamilCase commented
- Added `costPerHour`
- Added reserved prices mapping
- Changed API URLs
- Filtered out development environments

2021-12-23 16:44 UTC, omrivardi commented
Overall looks great. We need to figure the CORS issue.

Displaying some basic error on fetch failure could be a nice addition.

2021-12-27 09:42 UTC, omrivardi approved these changes
Great stuff.

The PR is ready. We need to validate the prices and the logic within with product

2021-12-27 13:04 UTC, kamilCase commented
Fixed the visual issue in the error container, as well as the warning that popped up with the introduction of `defineComponent(...)`

2021-12-27 15:20 UTC, omrivardi commented
The PR is blocked until we will merge and deploy the frontend server with the CORS PR.
A merge will trigger deployment that will currently break the calculator

2021-12-28 17:07 UTC, omrivardi requested changes

2021-12-29 15:12 UTC, omrivardi approved these changes

2022-01-14 13:12 UTC, map-r reviewed
you can check the comments

2022-01-16 08:21 UTC, omrivardi commented on widget/src/services/pricing.js
> +const HOURS_IN_MONTH = 730;
I think that considered being a short term solution, the actual subtle effect on the price in such case and the fact that this is an estimation calculator we can leave it as is.

2022-01-18 09:50 UTC, kamilCase commented on widget/src/services/pricing.js
> +      ondemand: Number(HOURS_IN_MONTH * instance.instanceCostHourly),
Of course it's not ;)

2022-01-18 10:15 UTC, kamilCase commented on widget/src/services/pricing.js
> +  return {
as you wish 😉

2022-01-27 07:13 UTC, merged